---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-builder-handler: regex:^dev-.*
  name: dennis-builder-handler
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-builder-handler
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-builder-handler:dev-18
        env:
        - name: LOG_LEVEL
          value: "info"
        name: dennis-builder-handler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-gateway: regex:^dev-.*
  name: dennis-gateway
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-gateway
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-gateway:dev-18
        env:
        - name: LOG_LEVEL
          value: "info"
        name: dennis-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-k8s-configurator: regex:^dev-.*
  name: dennis-k8s-configurator
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-k8s-configurator
      containers:
      - $setElementOrder/env:
        - name: LOG_LEVEL
        - name: VAULT_ADDR
        - name: VAULT_REPLICAS
        - name: VAULT_ADDR_PLACEHOLDER
        - name: CONSUL_HTTP_ADDR
        - name: HELM_RELEASE
        - name: POSTGRES_HOST
        - name: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_DBNAME
        - name: POSTGRES_SSL
        - name: BUILDER_WRAPPER_IMAGE
        - name: JAEGER_SAMPLING_SERVER_URL
        - name: JAEGER_LOCAL_AGENT_HOST_PORT
        - name: SECURITY_PROVIDER_CLIENT_ID
        - name: SECURITY_PROVIDER_CLIENT_SECRET
        - name: SECURITY_PROVIDER_OTP
        - name: SECURITY_PROVIDER_REALM
        - name: SECURITY_PROVIDER_TTL
        - name: SECURITY_PROVIDER_URL
        - name: AWS_BUCKET_NAME
        - name: AWS_REGION
        - name: KUBERNETES_DOCKER_REGISTRY
        - name: BUILDER_WRAPPER_DEADLINE_SEC
        - name: BUILDER_WRAPPER_CPU_LIMIT
        - name: BUILDER_WRAPPER_CPU_REQUEST
        - name: BUILDER_WRAPPER_MEM_LIMIT
        - name: BUILDER_WRAPPER_MEM_REQUEST
        - name: RUNNER_DEADLINE_SEC
        - name: RUNNER_CPU_LIMIT
        - name: RUNNER_CPU_REQUEST
        - name: RUNNER_MEM_LIMIT
        - name: RUNNER_MEM_REQUEST
        - name: LIVEPASS_URL
        - name: LIVEPASS_CALLBACK_URL
        - name: LIVEPASS_CALLBACK_CLIENT_ID
        - name: MIDDLEWARE_URL
        env:
        - name: LOG_LEVEL
          value: info
        image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-k8s-configurator:dev-18
        name: dennis-k8s-configurator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-middleware: regex:^dev-.*
  name: dennis-middleware
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-middleware
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-middleware:dev-56
        env:
        - name: API_URL
          value: "https://dennis.devdennis.zup.io"
        name: dennis-middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-portal: regex:^dev-.*
  name: dennis-portal
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-portal
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-portal:dev-56
        env:
        - name: MIDDLEWARE_URL
          value: "https://dennis-middleware.devdennis.zup.io"
        - name: LIVEPASS_ENDPOINT
          value: "https://idm-dev.continuousplatform.com/auth/realms/ZupDev/protocol/openid-connect"
        - name: LIVEPASS_CLIENT_ID
          value: "Dennis"
        - name: LIVEPASS_REDIRECT_URI
          value: "https://dennis-portal.devdennis.zup.io/callback"
        name: dennis-portal
