---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-builder-handler: regex:^dev-.*
  name: dennis-builder-handler
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-builder-handler
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-builder-handler:dev-10
        env:
        - name: CONSUL_HTTP_ADDR
          value: "http://dennis-consul-server:8500"
        - name: CONSUL_AUTH_METHOD
          value: "auth-method-consul-auth"
        - name: LOG_LEVEL
          value: "debug"
        name: dennis-builder-handler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-gateway: regex:^dev-.*
  name: dennis-gateway
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-gateway
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-gateway:dev-13
        name: dennis-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-k8s-configurator: regex:^dev-.*
  name: dennis-k8s-configurator
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-k8s-configurator
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-k8s-configurator:dev-13
        name: dennis-k8s-configurator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-middleware: regex:^dev-.*
  name: dennis-middleware
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-middleware
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-middleware:dev-55
        name: dennis-middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-portal: regex:^dev-.*
  name: dennis-portal
  namespace: dev-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-portal
      containers:
      - image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-portal:dev-55
        name: dennis-portal
