---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-builder-handler: regex:^stg-.*
  name: dennis-builder-handler
  namespace: stg-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-builder-handler
      containers:
      - $setElementOrder/env:
        - name: CONSUL_HTTP_ADDR
        - name: CONSUL_AUTH_METHOD
        - name: LOG_LEVEL
        env:
        - name: LOG_LEVEL
          value: warn
        image: 202035787030.dkr.ecr.sa-east-1.amazonaws.com/dennis-builder-handler:stg-5
        name: dennis-builder-handler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-gateway: regex:^stg-.*
  name: dennis-gateway
  namespace: stg-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-gateway
      containers:
      - $setElementOrder/env:
        - name: CONSUL_HTTP_ADDR
        - name: CONSUL_AUTH_METHOD
        - name: LOG_LEVEL
        - name: VAULT_ADDR
        - name: VAULT_AUTHENTICATION
        - name: VAULT_K8S_ROLE
        env:
        - name: LOG_LEVEL
          value: warn
        image: 202035787030.dkr.ecr.sa-east-1.amazonaws.com/dennis-gateway:stg-5
        name: dennis-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-k8s-configurator: regex:^stg-.*
  name: dennis-k8s-configurator
  namespace: stg-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-k8s-configurator
      containers:
      - $setElementOrder/env:
        - name: LOG_LEVEL
        - name: VAULT_ADDR
        - name: VAULT_REPLICAS
        - name: VAULT_ADDR_PLACEHOLDER
        - name: CONSUL_HTTP_ADDR
        - name: HELM_RELEASE
        - name: POSTGRES_HOST
        - name: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_DBNAME
        - name: POSTGRES_SSL
        - name: BUILDER_WRAPPER_IMAGE
        - name: JAEGER_SAMPLING_SERVER_URL
        - name: JAEGER_LOCAL_AGENT_HOST_PORT
        - name: SECURITY_PROVIDER_CLIENT_ID
        - name: SECURITY_PROVIDER_CLIENT_SECRET
        - name: SECURITY_PROVIDER_OTP
        - name: SECURITY_PROVIDER_REALM
        - name: SECURITY_PROVIDER_TTL
        - name: SECURITY_PROVIDER_URL
        - name: AWS_BUCKET_NAME
        - name: AWS_REGION
        - name: KUBERNETES_DOCKER_REGISTRY
        - name: BUILDER_WRAPPER_DEADLINE_SEC
        - name: BUILDER_WRAPPER_CPU_LIMIT
        - name: BUILDER_WRAPPER_CPU_REQUEST
        - name: BUILDER_WRAPPER_MEM_LIMIT
        - name: BUILDER_WRAPPER_MEM_REQUEST
        - name: RUNNER_DEADLINE_SEC
        - name: RUNNER_CPU_LIMIT
        - name: RUNNER_CPU_REQUEST
        - name: RUNNER_MEM_LIMIT
        - name: RUNNER_MEM_REQUEST
        - name: LIVEPASS_URL
        - name: LIVEPASS_CALLBACK_URL
        - name: LIVEPASS_CALLBACK_CLIENT_ID
        - name: MIDDLEWARE_URL
        env:
        - name: LOG_LEVEL
          value: warn
        image: 202035787030.dkr.ecr.sa-east-1.amazonaws.com/dennis-k8s-configurator:stg-5
        name: dennis-k8s-configurator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-middleware: regex:^stg-.*
  name: dennis-middleware
  namespace: stg-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-middleware
      containers:
      - $setElementOrder/env:
        - name: API_URL
        env:
        - name: API_URL
          value: https://dennis.stgdennis.zup.io
        image: 202035787030.dkr.ecr.sa-east-1.amazonaws.com/dennis-middleware:stg-13
        name: dennis-middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dennis-portal: regex:^stg-.*
  name: dennis-portal
  namespace: stg-test
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: dennis-portal
      containers:
      - $setElementOrder/env:
        - name: MIDDLEWARE_URL
        - name: LIVEPASS_ENDPOINT
        - name: LIVEPASS_CLIENT_ID
        - name: LIVEPASS_REDIRECT_URI
        env:
        - name: MIDDLEWARE_URL
          value: https://dennis-middleware.stgdennis.zup.io
        - name: LIVEPASS_REDIRECT_URI
          value: https://dennis-portal.stgdennis.zup.io/callback
        image: 202035787030.dkr.ecr.sa-east-1.amazonaws.com/dennis-portal:stg-13
        name: dennis-portal
