---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dennis-middleware
    app.kubernetes.io/name: dennis-middleware
  name: dennis-middleware
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: dennis-middleware
      app.kubernetes.io/name: dennis-middleware
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
      labels:
        app.kubernetes.io/instance: dennis-middleware
        app.kubernetes.io/name: dennis-middleware
    spec:
      shareProcessNamespace: true
      containers:
      - env:
        - name: API_URL
          value: "https://dennis.devdennis.zup.io"
        image: 731927492438.dkr.ecr.sa-east-1.amazonaws.com/dennis-middleware:dev-44
        imagePullPolicy: Always
        name: dennis-middleware
          #          livenessProbe:
          #            failureThreshold: 3
          #            httpGet:
          #              path: /metrics
          #              port: 3000
          #              scheme: HTTP
          #            initialDelaySeconds: 10
          #            periodSeconds: 30
          #            successThreshold: 1
          #            timeoutSeconds: 1
          #          readinessProbe:
          #            failureThreshold: 3
          #            httpGet:
          #              path: /metrics
          #              port: 3000
          #              scheme: HTTP
          #            initialDelaySeconds: 5
          #            periodSeconds: 10
          #            successThreshold: 1
          #            timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1536Mi
          requests:
            cpu: 128m
            memory: 256Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
