apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dennis-portal
    app.kubernetes.io/name: dennis-portal
  name: dennis-portal
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/instance: dennis-portal
    app.kubernetes.io/name: dennis-portal
  type: NodePort
