apiVersion: v1
kind: ServiceAccount
metadata:
  name: dennis-k8s-configurator-auth
  namespace: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-get-setter
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-getter
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: set-secret
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: dennis-k8s-configurator-auth
    namespace: dev
roleRef:
  kind: Role
  name: secret-get-setter
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-sa
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: dennis-k8s-configurator-auth
    namespace: dev
roleRef:
  kind: Role
  name: sa-getter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: dennis-k8s-configurator-auth
    namespace: dev