apiVersion: v1
kind: Service
metadata:
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app.kubernetes.io/instance: dennis-middleware
    app.kubernetes.io/name: dennis-middleware
  name: dennis-middleware
  namespace: dev
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app.kubernetes.io/instance: dennis-middleware
    app.kubernetes.io/name: dennis-middleware
  type: NodePort
