apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-auth-batch
  namespace: dev
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","list","get", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list","get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-auth-batch
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-auth-batch
subjects:
  - kind: ServiceAccount
    name: vault-auth
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-vault-auth
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: dev